name: Deploy to Streamlit

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust as needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Streamlit app
        run: streamlit run app_streamlit.py
